import streamlit as st
import pandas as pd
import google.generativeai as genai
from fpdf import FPDF


def generate_pdf_report(issue_key, summary, points, status, email_body):
    pdf = FPDF()
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 15, f"Executive Report: {issue_key}", ln=True, align="C")
    pdf.line(10, 25, 200, 25)  # Draw a horizontal line

    # Metadata Section
    pdf.set_font("Helvetica", "B", 12)
    pdf.ln(10)
    pdf.cell(0, 10, f"Project Summary: {summary}", ln=True)
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 10, f"Current Status: {status}", ln=True)
    pdf.cell(0, 10, f"Story Points: {points}", ln=True)

    # AI Content Section
    pdf.ln(10)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "AI-Generated Stakeholder Brief:", ln=True)
    pdf.set_font("Helvetica", "", 11)

    # Multi_cell handles text wrapping (no more manual line breaks!)
    pdf.multi_cell(0, 8, email_body)

    # Footer
    pdf.set_y(-25)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 10, "Generated by PM AI Dashboard - 2026", align="C")

    # Return the PDF as a binary string
    return pdf.output()


# --- 1. Cloud Secrets Setup ---_
api_key = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=api_key)
model = genai.GenerativeModel("gemini-2.5-flash")

st.title("📊 Universal Jira Dashboard")

# --- 2. The Dynamic File Uploader ---
# This replaces the hardcoded 'jira_export.csv'
uploaded_file = st.file_uploader("Upload your Jira Export (CSV)", type="csv")

if uploaded_file is not None:
    # If a user drops a file, we read it into memory
    df = pd.read_csv(uploaded_file)

    st.success("File loaded successfully!")

    st.divider()
    st.header("📈 Work Distribution")

    # 1. Prepare the data (The 'Pivot')
    # We group by Status and sum the Story Points
    chart_data = df.groupby("Status")["Story Points"].sum()

    # 2. Render the chart
    # In Java 2, this was 100 lines. Here, it's one.
    st.bar_chart(chart_data)

    # --- 3. Sidebar Selection ---
    # We use the 'Issue Key' column to fill the dropdown
    selected_issue = st.sidebar.selectbox("Select an Issue", df["Issue Key"])
    issue_data = df[df["Issue Key"] == selected_issue].iloc[0]

    # Create two tabs: one for the deep dive, one for the big picture
    tab1, tab2 = st.tabs(["🔍 Issue Detail", "📊 Team Analytics"])

    with tab1:
        st.subheader(f"Analysis for: {selected_issue}")
        # Move your existing Issue Details and AI Email logic here
        st.write(f"**Summary:** {issue_data['Summary']}")
        # ... (rest of your existing detail code)

    with tab2:
        st.subheader("Velocity & Status Distribution")

        # Calculate some quick metrics for the top of the tab
        total_points = df["Story Points"].sum()
        avg_points = df["Story Points"].mean()

        col_a, col_b = st.columns(2)
        col_a.metric("Total Story Points", total_points)
        col_b.metric("Avg Points per Task", f"{avg_points:.1f}")

        # Show the chart we just created
        st.bar_chart(chart_data)

        # Let's add a raw data view at the bottom
        with st.expander("See Raw Data Table"):
            st.dataframe(df)

    # --- 4. Dashboard Logic (The rest of your code) ---
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Issue Details")
        st.write(f"**Summary:** {issue_data['Summary']}")
        st.write(f"**Status:** {issue_data['Status']}")

    with col2:
        # Use the data from the CSV as the default
        points = st.slider(
            "Adjust Story Points", 1, 20, int(issue_data["Story Points"])
        )
        priority = st.text_input("Priority", value=issue_data["Priority"])

    # --- 5. The AI Feature ---
    st.divider()
    if st.button("Generate Stakeholder Email"):
        prompt = f"""
You are a Senior Project Manager. Write a professional status update email.
Task: {issue_data["Summary"]}
Status: {issue_data["Status"]}
Priority: {issue_data["Priority"]}

Formatting Instructions:
1. Use a clear **Subject Line**.
2. Use ## for the main heading.
3. Use **bolding** for critical dates or names.
4. Use bullet points for "Next Steps".
5. Keep the tone professional yet approachable.
"""
        with st.spinner("AI is drafting..."):
            response = model.generate_content(prompt)
            email_draft = response.text

            # --- REFINED OUTPUT DISPLAY ---
            st.subheader("Final Draft Review")

            # We use a container with a border to make it look like a 'document'
            with st.container(border=True):
                st.markdown(email_draft)  # This renders the bold, headers, and lists
                st.toast("Email Drafted Successfully!", icon="✉️")
                st.balloons()  # Use this sparingly, but it's fun for the first time!

            # Move the download button below the preview
            st.download_button(
                label="💾 Download as Text File",
                data=email_draft,
                file_name=f"Update_{selected_issue}.txt",
                mime="text/plain",
            )

            # Prepare the PDF binary data
            pdf_data = generate_pdf_report(
                selected_issue,
                issue_data["Summary"],
                issue_data["Story Points"],
                issue_data["Status"],
                email_draft,
            )

            # The "Executive" Download Button
            st.download_button(
                label="📄 Download Executive PDF Report",
                data=bytes(pdf_data),  # Convert to bytes for Streamlit
                file_name=f"Executive_Report_{selected_issue}.pdf",
                mime="application/pdf",
            )

else:
    # This part runs if NO file is uploaded
    st.warning("Welcome, PM! Please upload a CSV export to begin your analysis.")
    st.info("Tip: You can export a CSV directly from Jira's 'Issues' tab.")
    st.stop()  # This prevents the rest of the code from running/crashing
