import streamlit as st
import pandas as pd
import google.generativeai as genai
from fpdf import FPDF

from supabase import create_client, Client

# --- DB SETUP ---
url = st.secrets["SUPABASE_URL"]
key = st.secrets["SUPABASE_KEY"]
supabase: Client = create_client(url, key)


# --- SAVE TO DB FUNCTION ---
def save_report_to_db(issue_key, summary, email_body):
    data = {"issue_key": issue_key, "summary": summary, "email_body": email_body}
    # In 2026, we don't write "INSERT INTO..."
    # We use a clean Python "Post" method.
    supabase.table("reports").insert(data).execute()


def generate_pdf_report(issue_key, summary, points, status, email_body):
    pdf = FPDF()
    pdf.add_page()

    # 1. ADD THE LOGO
    # Use a direct URL to a logo (replace with your own!)
    # Tip: Use a PNG with a white or transparent background
    logo_url = "https://streamlit.io/images/brand/streamlit-logo-primary-colormark-darktext.png"

    # pdf.image(name, x, y, w)
    # x=10 (left), y=8 (top), w=33 (width in mm)
    try:
        pdf.image(logo_url, x=160, y=8, w=33)
    except:
        pass  # If the URL is broken, the PDF will still generate without the logo

    # 2. SANITIZE AND DRAW TEXT
    # Sanitize all inputs to avoid the FPDFUnicodeEncodingException
    safe_summary = sanitize_text(summary)
    safe_email = sanitize_text(email_body)

    pdf.set_font("Helvetica", "B", 20)
    pdf.ln(10)  # Move down a bit so we don't overlap the logo
    pdf.cell(0, 15, f"Executive Report: {issue_key}", ln=True, align="L")

    pdf.ln(10)
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 10, f"Project Summary: {safe_summary}", ln=True)  # Use safe version
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 10, f"Current Status: {status}", ln=True)
    pdf.cell(0, 10, f"Story Points: {points}", ln=True)

    # AI Content Section
    pdf.ln(10)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "AI-Generated Stakeholder Brief:", ln=True)
    pdf.set_font("Helvetica", "", 11)

    # Multi_cell handles text wrapping (no more manual line breaks!)
    # pdf.multi_cell(0, 8, email_body)
    pdf.multi_cell(0, 8, safe_email)  # Use safe version

    # Footer
    pdf.set_y(-25)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 10, "Generated by PM AI Dashboard - 2026", align="C")

    # Return the PDF as a binary string
    return pdf.output()


def sanitize_text(text):
    """Replaces common Unicode characters with PDF-safe equivalents."""
    if not text:
        return ""
    # Map of "Fancy" characters to "Plain" characters
    replacements = {
        "\u2013": "-",  # en-dash
        "\u2014": "-",  # em-dash
        "\u201c": '"',  # left curly quote
        "\u201d": '"',  # right curly quote
        "\u2018": "'",  # left single quote
        "\u2019": "'",  # right single quote
    }
    for unicode_char, ascii_char in replacements.items():
        text = text.replace(unicode_char, ascii_char)

    # Final safety net: encode to latin-1 and ignore anything that fails
    return text.encode("latin-1", "replace").decode("latin-1")


# --- 1. Cloud Secrets Setup ---_
api_key = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=api_key)
model = genai.GenerativeModel("gemini-2.5-flash")

# --- 2. THE SIDEBAR SECTION (Put this here!) ---
st.sidebar.title("⚙️ Project Settings")

# Theme Toggle
dark_mode = st.sidebar.toggle("Developer Dark Mode")

if dark_mode:
    st.markdown(
        """
        <style>
        .stApp { background-color: #0E1117; color: #FAFAFA; }
        [data-testid="stSidebar"] { background-color: #262730; }
        </style>
        """,
        unsafe_allow_html=True,
    )
else:
    st.markdown(
        """
        <style>
        .stApp { background-color: #FFFFFF; color: #31333F; }
        </style>
        """,
        unsafe_allow_html=True,
    )

st.sidebar.divider()  # Adds a nice visual line


st.title("📊 Universal Jira Dashboard")

# --- 2. The Dynamic File Uploader ---
# This replaces the hardcoded 'jira_export.csv'
uploaded_file = st.file_uploader("Upload your Jira Export (CSV)", type="csv")

if uploaded_file is not None:
    # If a user drops a file, we read it into memory
    df = pd.read_csv(uploaded_file)

    st.success("File loaded successfully!")

    st.divider()
    st.header("📈 Work Distribution")

    # 1. Prepare the data (The 'Pivot')
    # We group by Status and sum the Story Points
    chart_data = df.groupby("Status")["Story Points"].sum()

    # 2. Render the chart
    # In Java 2, this was 100 lines. Here, it's one.
    st.bar_chart(chart_data)

    # --- PROJECT HEALTH CALCULATION ---
    total_tasks = len(df)
    done_tasks = len(df[df["Status"] == "Done"])
    blocked_tasks = len(
        df[df["Status"] == "Blocked"]
    )  # Assumes your Jira has a 'Blocked' status

    # Calculate health percentage
    health_pct = (done_tasks / total_tasks) * 100 if total_tasks > 0 else 0

    # --- THE GAUGE DISPLAY ---
    st.subheader("🏥 Project Pulse")
    h_col1, h_col2, h_col3 = st.columns(3)

    with h_col1:
        # Green if many tasks are done
        st.metric(
            "Completion",
            f"{health_pct:.0f}%",
            delta=f"{done_tasks} Tasks",
            delta_color="normal",
        )

    with h_col2:
        # Red if we have blocked tasks
        # We use delta_color="inverse" so that positive numbers show as RED (because blocks are bad!)
        st.metric(
            "Blockers",
            blocked_tasks,
            delta="- Action Required" if blocked_tasks > 0 else "Clear",
            delta_color="inverse",
        )

    with h_col3:
        # A simple health status
        if blocked_tasks > 3:
            status_text = "CRITICAL"
            color = "🔴"
        elif blocked_tasks > 0:
            status_text = "WARNING"
            color = "🟡"
        else:
            status_text = "HEALTHY"
            color = "🟢"
        st.write(f"### Status: {color} {status_text}")

    # --- 3. Sidebar Selection ---
    # We use the 'Issue Key' column to fill the dropdown
    selected_issue = st.sidebar.selectbox("Select an Issue", df["Issue Key"])
    issue_data = df[df["Issue Key"] == selected_issue].iloc[0]

    # Create two tabs: one for the deep dive, one for the big picture
    # tab1, tab2 = st.tabs(["🔍 Issue Detail", "📊 Team Analytics"])

    # Add a third tab to your existing tab list
    tab1, tab2, tab3 = st.tabs(
        ["🔍 Issue Detail", "📊 Team Analytics", "📜 Report History"]
    )

    with tab1:
        st.subheader(f"Analysis for: {selected_issue}")
        # Move your existing Issue Details and AI Email logic here
        st.write(f"**Summary:** {issue_data['Summary']}")
        # ... (rest of your existing detail code)

    with tab2:
        st.subheader("Velocity & Status Distribution")

        # Calculate some quick metrics for the top of the tab
        total_points = df["Story Points"].sum()
        avg_points = df["Story Points"].mean()

        col_a, col_b = st.columns(2)
        col_a.metric("Total Story Points", total_points)
        col_b.metric("Avg Points per Task", f"{avg_points:.1f}")

        # Show the chart we just created
        st.bar_chart(chart_data)

        # Let's add a raw data view at the bottom
        with st.expander("See Raw Data Table"):
            st.dataframe(df)

    with tab3:
        st.subheader("Global Report Archive")
        # Fetch data from Supabase
        response = (
            supabase.table("reports")
            .select("*")
            .order("created_at", desc=True)
            .execute()
        )
        history_df = pd.DataFrame(response.data)

        if not history_df.empty:
            st.dataframe(history_df[["created_at", "issue_key", "summary"]])

            # Let the user pick an old report to view
            selected_report_id = st.selectbox("View Archived Email", history_df["id"])
            selected_text = history_df[history_df["id"] == selected_report_id][
                "email_body"
            ].values[0]
            st.info(selected_text)
        else:
            st.write("No reports found in the archive yet.")

    # --- 4. Dashboard Logic (The rest of your code) ---
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Issue Details")
        st.write(f"**Summary:** {issue_data['Summary']}")
        st.write(f"**Status:** {issue_data['Status']}")

    with col2:
        # Use the data from the CSV as the default
        points = st.slider(
            "Adjust Story Points", 1, 20, int(issue_data["Story Points"])
        )
        priority = st.text_input("Priority", value=issue_data["Priority"])

    # --- 5. The AI Feature ---
    st.divider()
    if st.button("Generate Stakeholder Email"):
        prompt = f"""
You are a Senior Project Manager. Write a professional status update email.
Task: {issue_data["Summary"]}
Status: {issue_data["Status"]}
Priority: {issue_data["Priority"]}

Formatting Instructions:
1. Use a clear **Subject Line**.
2. Use ## for the main heading.
3. Use **bolding** for critical dates or names.
4. Use bullet points for "Next Steps".
5. Keep the tone professional yet approachable.
"""
        with st.spinner("AI is drafting..."):
            response = model.generate_content(prompt)
            email_draft = response.text

            # --- REFINED OUTPUT DISPLAY ---
            st.subheader("Final Draft Review")

            # We use a container with a border to make it look like a 'document'
            with st.container(border=True):
                st.markdown(email_draft)  # This renders the bold, headers, and lists
                st.toast("Email Drafted Successfully!", icon="✉️")
                st.balloons()  # Use this sparingly, but it's fun for the first time!

            # NEW: Save to the cloud database automatically
            save_report_to_db(selected_issue, issue_data["Summary"], email_draft)
            st.success("Report saved to Database! ✅")

            # Move the download button below the preview
            st.download_button(
                label="💾 Download as Text File",
                data=email_draft,
                file_name=f"Update_{selected_issue}.txt",
                mime="text/plain",
            )

            # Prepare the PDF binary data
            pdf_data = generate_pdf_report(
                selected_issue,
                issue_data["Summary"],
                issue_data["Story Points"],
                issue_data["Status"],
                email_draft,
            )

            # The "Executive" Download Button
            st.download_button(
                label="📄 Download Executive PDF Report",
                data=bytes(pdf_data),  # Convert to bytes for Streamlit
                file_name=f"Executive_Report_{selected_issue}.pdf",
                mime="application/pdf",
            )

else:
    # This part runs if NO file is uploaded
    st.warning("Welcome, PM! Please upload a CSV export to begin your analysis.")
    st.info("Tip: You can export a CSV directly from Jira's 'Issues' tab.")
    st.stop()  # This prevents the rest of the code from running/crashing
